version: '2'

services:
  couchdb:
    container_name: couchdb                                                                                                                                      
    image: couchdb
    ports:
      - 5984:5984
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: adminpw
      DB_URL: http://localhost:5984/member_db
