version: '2'
services:
  ca0:
    image: hyperledger/fabric-ca:x86_64-1.0.0-alpha
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    ports:
      - 7054:7054
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/peerOrg1-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/d8a5b3cac1b821f6e4b487ceaf1fd239cdcfc310894150908b90f05e9179556a_sk -b admin:adminpw --tls.certfile /etc/hyperledger/tls/cas/peerOrg1/cert.pem --tls.keyfile /etc/hyperledger/tls/cas/peerOrg1/key.pem'
    volumes:
      - ./config/crypto-config/peerOrganizations/peerOrg1/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./config/tls:/etc/hyperledger/tls
    container_name: ca

  zookeeper:
    container_name: zookeeper
    image: hyperledger/fabric-zookeeper

  orderer0:
    container_name: orderer0
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - CONFIGTX_ORDERER_KAFKA_BROKERS=[kafka0:9092,kafka1:9092,kafka2:9092]
      - CONFIGTX_ORDERER_ORDERERTYPE=kafka
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_GENESISPROFILE=TwoOrgs
      - ORDERER_GENERAL_GENESISMETHOD=provisional
#      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/twoorgs.orderer.block
      - ORDERER_GENERAL_PROFILE_ENABLED=true # debug
#      - ORDERER_GENERAL_TLS_ENABLED=false
#      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
      - 6060:6060
    volumes:
      - ./config/channel/configtx.yaml:/etc/hyperledger/fabric/configtx.yaml
      - ./config/crypto-config/ordererOrganizations/ordererOrg1/orderers/ordererOrg1orderer1:/etc/hyperledger/fabric/msp/sampleconfig
    depends_on:
      - kafka0
      - kafka1
      - kafka2

  kafka0:
    container_name: kafka0
    image: hyperledger/fabric-kafka
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: "false"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  kafka1:
    container_name: kafka1
    image: hyperledger/fabric-kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: "false"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  kafka2:
    container_name: kafka2
    image: hyperledger/fabric-kafka
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: "false"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  peer0:
    container_name: peer0
    image: hyperledger/fabric-peer
    environment:
      - GOPATH=/opt/gopath
      - CORE_PEER_ID=peer0
      - CORE_PEER_ADDRESS=peer0:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0:7051
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_NEXT=true
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_PROFILE_ENABLED=true
#- CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_PEER_TLS_ENABLED=false
#      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/msp/sampleconfig/signcerts/peer0Signer.pem
#      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/msp/sampleconfig/keystore/peer0Signer.pem
#      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/msp/sampleconfig/cacerts/peerOrg0.pem
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=kafka_default
      #- CORE_PEER_ADDRESSAUTODETECT=true
      # - CORE_PEER_TLS_SERVERHOSTOVERRIDE=peer0
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start --peer-defaultchain=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/crypto-config/peerOrganizations/peerOrg1/peers/peerOrg1Peer1:/etc/hyperledger/fabric/msp/sampleconfig
      - ./foo.tx:/opt/gopath/src/github.com/hyperledger/fabric/foo.tx
      - ./example:/opt/gopath/src/github.com/hyperledger/fabric/example
    ports:
      - 7051:7051
      - 7053:7053
    depends_on:
      - orderer0

  peer1:
    container_name: peer1
    image: hyperledger/fabric-peer
    environment:
      - GOPATH=/opt/gopath
      - CORE_PEER_ID=peer1
      - CORE_PEER_ADDRESS=peer1:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1:8051
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_NEXT=true
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_PROFILE_ENABLED=true
#- CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_PEER_TLS_ENABLED=false
#      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/msp/sampleconfig/signcerts/peer0Signer.pem
#      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/msp/sampleconfig/keystore/peer0Signer.pem
#      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/msp/sampleconfig/cacerts/peerOrg0.pem
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=kafka_default
      #- CORE_PEER_ADDRESSAUTODETECT=true
      # - CORE_PEER_TLS_SERVERHOSTOVERRIDE=peer0
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start --peer-defaultchain=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/crypto-config/peerOrganizations/peerOrg1/peers/peerOrg1Peer2:/etc/hyperledger/fabric/msp/sampleconfig
    ports:
      - 8051:8051
      - 8053:8053
    depends_on:
      - orderer0


  couchdb0:
    container_name: couchdb0
    image: hyperledger/fabric-couchdb
    ports:
      - 5984:5984
